security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_JURY]
        ROLE_ADMIN: [ROLE_JURY]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            stateless: false
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                default_target_path: app_home
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
            logout:
                path: app_logout
                target: app_login

    access_control:

        # Allow anonymous access to login, registration, and home
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/registration, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }

        # Role-specific access
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_JURY] }
        - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/jury, roles: ROLE_JURY }
        - { path: ^/jury, roles: ROLE_JURY }

        # For app_apply_page
        - { path: ^/application/finish, roles: ROLE_CANDIDATE }
        - { path: ^/registration, roles: ROLE_CANDIDATE }
        - { path: ^/reservation, roles: ROLE_CANDIDATE }
        - { path: ^/validate/email, roles:  [ROLE_ADMIN, ROLE_JURY, ROLE_CANDIDATE] }
        - { path: ^/profile/completion, roles:  [ROLE_ADMIN, ROLE_JURY, ROLE_CANDIDATE] }
        - { path: ^/profile, roles:  [ROLE_ADMIN, ROLE_JURY, ROLE_CANDIDATE] }
        - { path: ^/planning, roles:  [ROLE_ADMIN, ROLE_JURY, ROLE_CANDIDATE] }
        - { path: ^/apply/apply/confirmation, roles:  [ROLE_CANDIDATE] }
        - { path: ^/apply/finish, roles:  [ROLE_CANDIDATE] }
        - { path: ^/apply/confirmation, roles:  [ROLE_CANDIDATE] }
