controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_404:
    path: /{any}
    controller: App\Controller\FourOFourController::index
    requirements:
        any: .*
